### ISSUE TITLE
Able to use with other player? 

### ISSUE THREAD

**Issue by harrykc** [Okazari/Rythm.js#12]
Thanks for the great work, i am using orher music player called APlayer. Can I add the rythm into the this player? It means the audio come from other player.

Or can you give me some tips how to add it?  Thanks again

**Comment by HaykoKoryun** [comment]
I think it would be fairly simple to implement. One option from a cursory look is to modify the [`setMusic`](https://github.com/Okazari/Rythm.js/blob/master/src/rythm.js#L50) function to be polymorphic so that if an actual `Audio` object is passed instead of a `String` it uses the existing `Audio` object.

**Comment by Okazari** [comment]
I'm currently working on a new API method for `Rythm.js` that can use an `AudioElement` instead of a `String` this one will just read audio and not control it. First major problem is that APlayer is not exposing its `audioContext` and an `AudioElement` can only be connected once.

Investigating for a solution...

**Comment by Okazari** [comment]
Got a solution that works, going to clean the code and push it :)

**Comment by Okazari** [comment]
You will be able to works with APlayer by doing this :

```js
rythm.connectExternalAudioElement(ap.audio)
rythm.start();
```

**Comment by harrykc** [comment]
This is awesome, its working, thanks for your great work.

**Comment by Okazari** [comment]
You're welcome ! 😄

**Comment by harrykc** [comment]
I found a strange issue, the animation will stop after few songs played(do not know how many, i have not count it). In APlayer, i am doing following code in play event.
```
ap.on('play', function() {
    rythm.connectExternalAudioElement(ap.audio);
    rythm.start();
})

```

I am debuging with it, but still no idea how to trigger it.

**Comment by Okazari** [comment]
Thx for the feedback ! Did you had this issue more that once ?

Sometimes the preconfigured classes won't react on some songs. (Songs that don't use this frequencies)

**Comment by harrykc** [comment]
Once trigger this issue, then the animation will stop, even for the next, next song.

**Comment by harrykc** [comment]
For this issue, i think this is the reason

![2017-02-24_221753](https://cloud.githubusercontent.com/assets/7317546/23306605/38ae55ec-fadf-11e6-91f2-fc1714329dc0.png)

and i found this article http://stackoverflow.com/questions/35492397/remove-createmediaelementsource
any idea?
