### ISSUE TITLE
How to use Rythm.js with 0 Volume?

### ISSUE THREAD

**Issue by PromptJar** [Okazari/Rythm.js#136]
Is there a way to use Rythm.js with 0 Volume?

My audio source comes from a YT video. Rythm doesn't connect to the YT embed so I am using the same audio track as the YT video and starting both at the same time.

Synchronization isn't a major issue since the audio that you hear comes from the video, so the video and audio don't lose sync. 

My issue is muting the Rythm sound, but keeping it working.

Is there a way to do that? I have tried creating a dummy AudioContext and setting the gain to 0, as well as using a custom Audio element, but nothing seems to work. When the audio has no volume or gain, Rythm stops working.

```
 const AudioContext = window.AudioContext || window.webkitAudioContext;
 const audioCtx = new AudioContext();

// Create a null gain node with an input and an output
const nullDestination = audioCtx.createGain();
nullDestination.gain.value = 0;
audioCtx.destination.disconnect();
audioCtx.destination.connect(nullDestination);

const rythm = new Rythm(audioCtx)
```

This either doesn't work with Rythm or throws this error:
`IndexSizeError: Failed to execute 'connect' on 'AudioNode': output index (0) exceeds number of outputs (0).`

Have I missed something?  Is this literally impossible? 

Is there a way to mute or not hear the Rythm sound source while still keeping it working? Any help or suggestions would be immensly appreciated. Thank you!

**Comment by Okazari** [comment]
Hello @PromptJar first, thanks for using Rythm.js 😄 

Right now this isn't a feature that i had in my mind and Rythm.js animation is tied to the volume.

I think we might want to add an option around here https://github.com/Okazari/Rythm.js/blob/62799156982e31081c45171664cdb5d3c6cbe328/src/Player.js#L43 that either doesn't connect the rythm.js player to the audioContext destination or add another gain that mute the sound right before connecting to the audio destination.

```js
if(!noOutput) {
      Analyser.analyser.connect(this.audioCtx.destination)
}
```

or

```js
if(!noOutput) {
  const muteNode = this.audioCtx.createGain()
  muteNode.gain = 0
  Analyser.analyser.connect(muteNode)
  muteNode.connect(this.audioCtx.destination)
} else {
  Analyser.analyser.connect(this.audioCtx.destination)
}
```

Unfortunatly, either way, it will require to update Rythm.js internal code in order to do that 😢.

I can't say when i'll have the time to do that, if you really want that feature, feel free to create a PR 👍 I'll try to merge it and deploy the new version right away.

**Comment by PromptJar** [comment]
So I took your snippet above and modified the node_modules source (quick & dirty). 

This is the part I changed:
```
this.connectSource = function (source) {
    source.connect(_this.gain);
    _this.gain.connect(Analyser$1.analyser);
    if (_this.currentInputType !== _this.inputTypeList['STREAM']) {
      // Analyser$1.analyser.connect(_this.audioCtx.destination); // COMMENTED OUT

     // NEW CODE
      const muteNode = _this.audioCtx.createGain()
      muteNode.gain = 0
      Analyser$1.analyser.connect(muteNode);
      muteNode.connect(_this.audioCtx.destination)


      _this.audio.addEventListener('ended', _this.stop);
    } else {
      Analyser$1.analyser.disconnect();
    }
  };
```

Unfortunately nothing happens (audio plays with sound), and I'm really bad at audio 😥

Will try a few different things but first I'll check how this all works.

**Comment by Okazari** [comment]
Arg, I though that would do the trick. 
Did you try the first option (by only removing the `analyser.connect(audioCtx.destination)` instruction) ?

Also, are you completely sure the modified source in the `node_modules` are loaded ? There might be some cache involved that could prevent your modifications to be applied. (You could check that by adding a quick `console.log`).
If modifications aren't working, you could checkout the Rythm.js repository and link it in your project (I usually use `yarn` with the `yarn link`).

Could you share a bit more code on how you integrated Rythm.js ?
Ideally, could you share a minimal reproduction of your use case ? (On codesandbox or similar). So that I could try to investigate a bit a more 👍

**Comment by PromptJar** [comment]
Add caching to the list of stuff I'm not good at 😰

The `muteNode.gain = 0` part will not work as it throws an error about it being only a getter.

However, just commeting out the first line like you initially said works perfectly.

Thanks for holding my hand here!
