### ISSUE TITLE
Not working on android

### ISSUE THREAD

**Issue by Okazari** [Okazari/Rythm.js#4]
Tried the demo page on android, and it's all crappy 😭  !

**Comment by LeoLamCY** [comment]
works fine here on android using chrome v55 unless you are referring to some button's positions being slightly off center?

Your demo page doesn't seem to be in this repo so I will just make a suggestion on how to fix it here:
You will need to remove
`.btn + .btn {
    margin-left: 1rem;
}`
from custom.css because it is redundant and is overwriting your media queries for mobile browsers in your main stylesheet, resulting in some buttons being shifted to the right by 1 rem.

**Comment by Okazari** [comment]
Thanks for the feedback ! Autoplay wasn't working on mine. But if i click on the start track button it works ! It's just a bit laggy tho. 
If you want to PR your css adjustement, the public demo is on this repo on the gh-page branch.

If you dont want to, I'll probably fix this later on.

**Comment by HaykoKoryun** [comment]
AFAIK you can't have autoplay on mobile devices, you need to have the user interact with the page first and play the audio track using the scope of the interaction; so it's strictly not a bug.
